---
- name: maps
  hosts: map_server
  become: yes
  remote_user: ansible
  vars:
    project_name: maps
    search_server: www.search.kartan.no
    project_dir: home/{{remote_user}}/{{project_name}}
  # roles:
    # - 
    # - elasticsearch 
    # - node
  tasks:
  - name: apt get update
    apt: update_cache=yes
  - name: install git
    apt: name=git state=present


  - name: gdal repo
    apt_repository: repo='deb ppa:ubuntugis/ubuntugis-unstable' state=present
  # - name: install zlib
  #   apt: name=zlib1g-dev state=present
  # - name: get ctb-tiler
  #   git: repo=https://github.com/geo-data/cesium-terrain-builder force=yes update=yes dest={{project_dir}}/cesium-terrain-builder accept_hostkey=True

  # 